FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["c:\\bezAV\\BeefProjjj\\BeefLog\\Example\\src\\Program.bf", "src\\Logger.bf", "src\\Types\\LogMessage.bf", "src\\Enums\\Level.bf"]

[MainWindow]
X = 394
Y = 146
Width = 1472
Height = 1014
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 312.0
RequestedHeight = 1335.0
SizePriority = 1335.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 150.0
RequestedHeight = 809.0
SizePriority = 809.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 233.0
RequestedHeight = 312.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 0.5195946
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Logger.bf"
TabWidth = 96.0
Type = "SourceViewPanel"
FilePath = "src\\Logger.bf"
CursorPos = 542
VertPos = 378.0
ProjectName = "BeefLog"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
IsFillWidget = true
RequestedWidth = 1476.0
RequestedHeight = 809.0
SizePriority = 0.4804054
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "LogMessage.bf"
TabWidth = 130.0
Type = "SourceViewPanel"
FilePath = "src\\Types\\LogMessage.bf"
CursorPos = 226
ProjectName = "BeefLog"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Level.bf"
TabWidth = 84.0
Type = "SourceViewPanel"
FilePath = "src\\Enums\\Level.bf"
CursorPos = 76
ProjectName = "BeefLog"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 106.0
Type = "SourceViewPanel"
FilePath = "c:\\bezAV\\BeefProjjj\\BeefLog\\Example\\src\\Program.bf"
CursorPos = 243
ProjectName = "Example"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 205.0
RequestedHeight = 236.5
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Class View"
TabWidth = 111.0
Type = "ClassViewPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 312.0
RequestedHeight = 284.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 312.0
RequestedHeight = 312.0
SizePriority = 0.4796663
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 130.0
Type = "AutoWatchPanel"
Columns = [{Width = 149.0}, {Width = 661.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 87.0
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 101.0
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Errors"
TabWidth = 86.0
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 118.0
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 434.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 222.0}, {Width = 250.0}, {Width = 112.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 312.0
RequestedHeight = 312.0
SizePriority = 0.5203336
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"
